import os
import sys
from pathlib import Path

import requests
from dotenv import load_dotenv
from ruamel.yaml import YAML
from ruamel.yaml.comments import CommentedMap

load_dotenv()

ROOT_DIR = Path(__file__).resolve().parent.parent
REPOS_YAML = ROOT_DIR / "repos.yaml"
CATEGORY_MD = ROOT_DIR / "CATEGORY.md"

UNCATEGORIZED = "未分類"
META_GROUP = "管理"
DEFAULT_CONTENT_REPO = "wiki"
DEFAULT_ORG_REPOS = {"portal", "wiki"}
CATEGORY_HEADER = "<!-- This file is generated by .scripts/generate_profile_readme.py. Do not edit manually. -->"

yaml = YAML()
yaml.preserve_quotes = True
yaml.indent(mapping=2, sequence=4, offset=2)


def load_config():
    return yaml.load(REPOS_YAML.read_text(encoding="utf-8"))


def content_repo(config):
    return config.get("content_repo", DEFAULT_CONTENT_REPO)


def org_repos(config):
    configured = config.get("org_repos")
    if configured:
        return {str(name).lower() for name in configured}
    return {name.lower() for name in DEFAULT_ORG_REPOS}


def iter_categories(config):
    for group in config["groups"]:
        for category in group["categories"]:
            yield category


def listed_names(config):
    names = set()
    for category in iter_categories(config):
        for repo in category["repos"] or []:
            names.add(str(repo["name"]).lower())
    return names


def auth_headers(token):
    headers = {"Accept": "application/vnd.github+json"}
    if token:
        headers["Authorization"] = f"Bearer {token}"
    return headers


def fetch_wiki_topics(org, repo, token):
    url = f"https://api.github.com/repos/{org}/{repo}/contents/"
    response = requests.get(url, headers=auth_headers(token), timeout=60)
    response.raise_for_status()
    data = response.json()
    if not isinstance(data, list):
        return []
    return sorted(
        item["name"]
        for item in data
        if item.get("type") == "dir" and not item["name"].startswith(".")
    )


def ensure_repos_list(category):
    if category.get("repos") is None:
        category["repos"] = []


def uncategorized_category(config):
    for category in iter_categories(config):
        if category.get("name") == UNCATEGORIZED:
            ensure_repos_list(category)
            return category

    meta_group = None
    for group in config["groups"]:
        if group["name"] == META_GROUP:
            meta_group = group
            break
    if meta_group is None:
        meta_group = CommentedMap()
        meta_group["name"] = META_GROUP
        meta_group["categories"] = []
        config["groups"].append(meta_group)

    category = CommentedMap()
    category["name"] = UNCATEGORIZED
    category["repos"] = []
    meta_group["categories"].append(category)
    return category


def add_topic(category, name):
    ensure_repos_list(category)
    entry = CommentedMap()
    entry["name"] = name
    entry["memo"] = ""
    entry.fa.set_flow_style()
    category["repos"].append(entry)


def sync_with_wiki(config, wiki_topics):
    listed = listed_names(config)
    new_topics = sorted(name for name in wiki_topics if name.lower() not in listed)

    if new_topics:
        category = uncategorized_category(config)
        for name in new_topics:
            add_topic(category, name)
        print(f"Added {len(new_topics)} new topic(s) to {UNCATEGORIZED}: {', '.join(new_topics)}")

    wiki_lower = {name.lower() for name in wiki_topics}
    reserved = org_repos(config)
    for category in iter_categories(config):
        for repo in category["repos"] or []:
            name = str(repo["name"])
            if name.lower() in reserved:
                continue
            if name.lower() not in wiki_lower:
                print(f"WARNING: '{name}' is listed but not found in {content_repo(config)}")

    return new_topics


def content_branch(config):
    return config.get("content_branch", "main")


def topic_url(org, config, name):
    if name.lower() in org_repos(config):
        return f"https://github.com/{org}/{name}"
    repo = content_repo(config)
    branch = content_branch(config)
    return f"https://github.com/{org}/{repo}/tree/{branch}/{name}"


def group_has_repos(group):
    for category in group["categories"]:
        if category["repos"]:
            return True
    return False


def heading_anchor(name):
    return name


def render_category(category, org, config):
    repos = category["repos"] or []
    if not repos:
        return None
    lines = []
    if not category.get("flat"):
        lines.extend([f"### {category['name']}", ""])
    lines.extend([
        "| Repository | Repository URL | Memo |",
        "| --- | --- | --- |",
    ])
    for repo in repos:
        name = repo["name"]
        memo = repo.get("memo") or ""
        url = topic_url(org, config, name)
        lines.append(f"| `{name}` | [GitHub]({url}) | {memo} |")
    return "\n".join(lines)


def render_overview_table(config):
    rows = []
    for group in config["groups"]:
        if not group_has_repos(group):
            continue
        name = group["name"]
        anchor = heading_anchor(name)
        description = group.get("description") or ""
        rows.append(f"| [{name}](#{anchor}) | {description} |")
    if not rows:
        return ""
    return "\n".join([
        "## カテゴリ一覧",
        "",
        "| カテゴリ | 説明 |",
        "| --- | --- |",
        *rows,
    ])


def render_group_header(name):
    anchor = heading_anchor(name)
    return f'<a id="{anchor}"></a>\n\n## {name}'


def render_tables(config, org):
    blocks = []
    for group in config["groups"]:
        category_blocks = [
            block
            for category in group["categories"]
            if (block := render_category(category, org, config)) is not None
        ]
        if not category_blocks:
            continue
        header = render_group_header(group["name"])
        blocks.append("\n\n".join([header, *category_blocks]))
    return "\n\n".join(blocks)


def build_category_md(overview, body):
    sections = [section for section in (overview, body) if section]
    return f"{CATEGORY_HEADER}\n\n" + "\n\n".join(sections) + "\n"


def dump_yaml(config):
    from io import StringIO

    stream = StringIO()
    yaml.dump(config, stream)
    return stream.getvalue()


def format_new_topics_for_pr(new_topics, org, config):
    return "\n".join(
        f"- [`{name}`]({topic_url(org, config, name)})" for name in new_topics
    )


def format_pr_title_suffix(new_topics):
    if len(new_topics) <= 3:
        return ", ".join(new_topics)
    return f"{new_topics[0]} +{len(new_topics) - 1} more"


def uncategorized_topic_names(config):
    for category in iter_categories(config):
        if category.get("name") == UNCATEGORIZED:
            return [str(repo["name"]) for repo in category["repos"] or []]
    return []


def write_github_output(changed, new_topics_added, new_topics, org, config, uncategorized_empty):
    output_path = os.getenv("GITHUB_OUTPUT")
    if not output_path:
        return
    with open(output_path, "a", encoding="utf-8") as handle:
        handle.write(f"changed={'true' if changed else 'false'}\n")
        handle.write(f"new_repos_added={'true' if new_topics_added else 'false'}\n")
        handle.write(f"uncategorized_empty={'true' if uncategorized_empty else 'false'}\n")
        if new_topics:
            handle.write(f"pr_title_suffix={format_pr_title_suffix(new_topics)}\n")
            handle.write("new_repos_body<<EOF\n")
            handle.write(format_new_topics_for_pr(new_topics, org, config))
            handle.write("\nEOF\n")


def main():
    check_only = "--check" in sys.argv

    config = load_config()
    org = config.get("org", "lvncerpedia")
    wiki = content_repo(config)
    new_topics = []

    token = os.getenv("GITHUB_TOKEN")
    if token:
        wiki_topics = fetch_wiki_topics(org, wiki, token)
        print(f"Fetched {len(wiki_topics)} topics from '{org}/{wiki}'")
        new_topics = sync_with_wiki(config, wiki_topics)
    else:
        print(f"No GITHUB_TOKEN: skipping wiki sync, rendering from repos.yaml only")

    new_topics_added = bool(new_topics)
    uncategorized_empty = not uncategorized_topic_names(config)
    new_yaml = dump_yaml(config)
    overview = render_overview_table(config)
    body = render_tables(config, org)
    new_category = build_category_md(overview, body)

    current_yaml = REPOS_YAML.read_text(encoding="utf-8")
    current_category = CATEGORY_MD.read_text(encoding="utf-8") if CATEGORY_MD.exists() else ""
    category_changed = new_category != current_category
    yaml_changed_by_sync = new_topics_added and new_yaml != current_yaml
    changed = category_changed or yaml_changed_by_sync

    if check_only:
        if changed:
            print("CHECK FAILED: repos.yaml or CATEGORY.md is out of date. Run the generator.")
            write_github_output(changed, new_topics_added, new_topics, org, config, uncategorized_empty)
            sys.exit(1)
        print("CHECK OK: portal is up to date")
        write_github_output(False, False, [], org, config, uncategorized_empty)
        return

    if not changed:
        print("No changes")
        write_github_output(False, False, [], org, config, uncategorized_empty)
        return

    if new_topics_added:
        REPOS_YAML.write_text(new_yaml, encoding="utf-8")
    if category_changed:
        CATEGORY_MD.write_text(new_category, encoding="utf-8")

    write_github_output(changed, new_topics_added, new_topics, org, config, uncategorized_empty)
    print("Updated repos.yaml and CATEGORY.md" if new_topics_added else "Updated CATEGORY.md")


if __name__ == "__main__":
    main()
